// Generated by CoffeeScript 1.6.2
(function() {
  $.getJSON('http://zh.moegirl.org/api.php?action=query&list=recentchanges&rcnamespace=0&rctoponly=true&rctype=edit&format=json&callback=?', function(data) {
    var item, _i, _len, _ref, _results;

    _ref = data.query.recentchanges;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      item = _ref[_i];
      console.log(item);
      _results.push($('<li/>', {
        "class": 'item'
      }).append($('<a />', {
        href: "http://zh.moegirl.org/" + item.title,
        text: item.title,
        "class": 'title',
        target: '_blank'
      })).appendTo('.moegirlwiki-widgets .items'));
    }
    return _results;
  });

}).call(this);
